# Generated by Django 5.2.3 on 2025-06-23 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Brainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="contactus",
            name="issue_type",
            field=models.CharField(
                choices=[
                    ("Bug Report", "Bug Report"),
                    ("Feature Request", "Feature Request"),
                    ("System Imporvment", "System Imporvment"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ID must be D### for doctors, R### for admins, or 14-digit for patients.",
                        regex="^((D|R)\\d{3}|\\d{14})$",
                    )
                ],
                verbose_name="National ID",
            ),
        ),
    ]
